# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

use_frameworks!

target 'MarcoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for MarcoApp
  
#  pod 'HockeySDK'

pod 'GoogleMaps'
pod 'GooglePlaces'

pod 'PubNub' #, "~> 4"

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'Fabric', '~> 1.8.2'
pod 'Crashlytics', '~> 3.11.1'

pod 'AlamofireObjectMapper', '~> 5.0'
pod 'ObjectMapper'

pod 'Alamofire', '~> 4.5'

pod 'SDWebImage', '~> 4.0'
pod 'PKHUD'
#pod 'CropViewController'


pod 'FCAlertView'

pod 'MagicalRecord'

#pod 'MessageKit'

#pod 'TwitterKit'

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

pod 'Stripe'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
    end
end

